### PR TITLE
Update newFile.html

### PR DESCRIPTION
**Pull request by p00j4**
Live from conference

### CODE REVIEW

**Comment by p00j4** [comment]
Did you remember to?
- [ ] Add Test Case(s)- [ ] P0 Tests Executed EndToEnd?

**Comment by p00j4** [comment]
Did you remember to?
- [ ] Add Test Case(s)- [ ] P0 Tests Executed EndToEnd?

**Comment by p00j4** [comment]
Did you remember to?
- [ ] Add Test Case(s)- [ ] P0 Tests Executed EndToEnd?

**Comment by p00j4** [comment]
Did you remember to?
- [ ] Add Test Case(s)
- [ ] P0 Tests Executed EndToEnd?

**Comment by moeoperation** [comment]
Did you remember to?
- [ ] Add Test Case(s)
- [ ] P0 Tests Executed EndToEnd?

**Comment by moeoperation** [comment]
Did you remember to?
- [ ] Add Test Case(s)
- [ ] P0 Tests Executed EndToEnd?

**Comment by moeoperation** [comment]
Did you remember to?
- [ ] Add Test Case(s)
- [ ] P0 Tests Executed EndToEnd?

**Comment by moeoperation** [comment]
Did you remember to?
- [ ] Add Test Case(s)
- [ ] P0 Tests Executed EndToEnd?

**Pull request merged**
